app:
  build: .
  command: nodemon bin/www.js
  volumes:
    - .:/usr/src/app
  ports:
    - ':3000'
  environment:
    AUTH_HOST: https://staging-auth.sovee.com
    AUTH_TOKEN: fe56002db2632cd72daff4ac496aac1cfec7577b 
    DB_HOST: db 
    PARALLEL_HOST: https://staging-parallel-api.sovee.com
    ALCHEMY_HOST: https://staging-alchemy.sovee.com
    ALCHEMY_AUTH_TOKEN: 664d6eaa2015f05a81210aaa398c292d6f4bd641
  links:
    - db
    - redis
db:
  image: mongo:2.6
redis:
  image: redis:latest
