app:
  build: .
  command: nodemon bin/www.js
  volumes:
    - .:/usr/src/app
  ports:
    - ':3000'
  environment:
    AUTH_HOST: https://staging-auth.sovee.com
    AUTH_TOKEN: fe56002db2632cd72daff4ac496aac1cfec7577b
    DB_HOST: db
    PARALLEL_HOST: https://usfx.herokuapp.com
    ALCHEMY_HOST: https://staging-alchemy.sovee.com
    ALCHEMY_AUTH_TOKEN: 664d6eaa2015f05a81210aaa398c292d6f4bd641
    ALCHEMY_CUSTOMER: Sovee
    S3_KEY: AKIAJEGTNC6WJFSOSX6A
    S3_SECRET: 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
    S3_BUCKET: sovee-bible-app
    AWS_HOST: https://s3.amazonaws.com
    AWS_ENV: development
    TEMP: /tmp
  links:
    - db
    - redis
db:
  image: mongo:2.6
redis:
  image: redis:latest
