apiVersion: v1
kind: ReplicationController
metadata:
  name: staging-bible-api-v1.0.0  # Name of the RC
spec:
  replicas: 3                # How many copies of your pod you want to run
  selector:                  # Set of selectors for matching pods this RC should maintain
    name: bible-api
    environment: staging
    role: app
    deployment: v1.0.0
  template:                  # Pod template to use when this RC creates pods
    metadata:
      labels:                # Labels to use for the pods created by this RC
        name: bible-api
        environment: staging
        role: app
        deployment: v1.0.0
    spec:
      terminationGracePeriodSeconds: 15  # How much time to give your pods before force killing them
      imagePullSecrets:                  # Keys needed by docker to pull private repository images from docker hub
        - name: dockerhubkey
      containers:                        # List of containser in this pod
        - name: app                      # Name of the container
          image: sovee/bible-api:latest          # Image to use for the container
          command:                       # Command to execute when starting the container (Not needed if you have a CMD in your Dockerfile instead)
            - nodemon
            - app.js
          ports:                         # List of ports your app will use
            - name: app                  # Name for the port (Not required if there is only 1 port)
              containerPort: 3000        # Port your app will listen on
          imagePullPolicy: Always        # Tells docker to always pull the image instead of using local cache of the image (good if your using a tag like :latest)
          env:                           # List of environment variables to set in the container
            - name: AUTH_HOST
              value: "http://staging-auth"
            - name: DB_HOST
              value: 'staging-bible-api.cyix5mbukl1b.us-east-1.rds.amazonaws.com'
            - name: DB_NAME
              value: 'bible-api-data'
            - name: DB_USER
              value: 'bible-api'
            - name: DB_PASS
              value: 'b76315eda9e149d5b4bf6c5f725f4278'
            - name: DB_PORT
              value: '3306'
